### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by djimrand** [lcx366/GGTOOLS#3]
Hello everyone. 
My name is Randal D. DJESSOU. I'm in master degree, option: Geodesy.
My research Topic is about Groundwater. So, I'm using ggtools package to estimate TWS from GLDAS data I downloaded using the same package. But when I used read_gldas function to read GLDAS data I got some issue like:

Python 3.7.7 (default, May  6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from ggtools.gg import read_gldas
>>> gldas = read_gldas()
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\xarray\backends\file_manager.py", line 198, in _acquire_with_cache_info
    file = self._cache[self._key]
  File "C:\ProgramData\Anaconda3\lib\site-packages\xarray\backends\lru_cache.py", line 53, in __getitem__
    value = self._cache[key]
KeyError: [<class 'netCDF4._netCDF4.Dataset'>, ('C:\\Users\\DJIMRAND\\GLDAS\\NOAH10\\GLDAS_NOAH10_M.A200204.021.nc4',), 'r', (('clobber', True), ('diskless', False), ('format', 'NETCDF4'), ('persist', False))]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\ggtools\gg\gldas_utils.py", line 181, in read_gldas
    datum = xr.open_dataset(filename)
  File "C:\ProgramData\Anaconda3\lib\site-packages\xarray\backends\api.py", line 509, in open_dataset
    filename_or_obj, group=group, lock=lock, **backend_kwargs
  File "C:\ProgramData\Anaconda3\lib\site-packages\xarray\backends\netCDF4_.py", line 358, in open
    return cls(manager, group=group, mode=mode, lock=lock, autoclose=autoclose)
  File "C:\ProgramData\Anaconda3\lib\site-packages\xarray\backends\netCDF4_.py", line 314, in __init__
    self.format = self.ds.data_model
  File "C:\ProgramData\Anaconda3\lib\site-packages\xarray\backends\netCDF4_.py", line 367, in ds
    return self._acquire()
  File "C:\ProgramData\Anaconda3\lib\site-packages\xarray\backends\netCDF4_.py", line 361, in _acquire
    with self._manager.acquire_context(needs_lock) as root:
  File "C:\ProgramData\Anaconda3\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\ProgramData\Anaconda3\lib\site-packages\xarray\backends\file_manager.py", line 186, in acquire_context
    file, cached = self._acquire_with_cache_info(needs_lock)
  File "C:\ProgramData\Anaconda3\lib\site-packages\xarray\backends\file_manager.py", line 204, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
  File "netCDF4\_netCDF4.pyx", line 2358, in netCDF4._netCDF4.Dataset.__init__
  File "netCDF4\_netCDF4.pyx", line 1926, in netCDF4._netCDF4._ensure_nc_success
OSError: [Errno -51] NetCDF: Unknown file format: b'C:\\Users\\DJIMRAND\\GLDAS\\NOAH10\\GLDAS_NOAH10_M.A200204.021.nc4'

So, I pretty need your help. Thanks you in advance.

**Comment by Bownnw** [comment]
Maybe you could` conda uninstall netcdf4`
and `pip install netcdf4`

**Comment by shubhawasthi123** [comment]
# for signal leakage correction with inverse filtering

gsm_twsc_series = gsm_r_ddk5_sma_leakage_series - twsc_grid_series
gsm_twsc_series_rate = gsm_twsc_series.rate()
fig_name = 'GRACE_TWSC_series.png'
gsm_twsc_series.plot(fig_name,'ylabel',kernel='rbf')
![Screenshot from 2023-04-08 15-38-51](https://user-images.githubusercontent.com/33890673/230715683-e830ca9d-b198-4d8a-a8cf-93febce9c708.png)
