### ISSUE TITLE
ImportError: cannot import name 'create_polygon' from 'sphericalpolygon' 

### ISSUE THREAD

**Issue by xiaoledeng** [lcx366/GGTOOLS#4]
Traceback (most recent call last):
  File "001_GRACE_Download_static_gravity_models.py", line 7, in <module>
    from ggtools.gg import static_download
  File "/Users/shalom/anaconda3/lib/python3.7/site-packages/ggtools/gg/__init__.py", line 116, in <module>
    from .gsm_utils import print_gsm_date_coverage,gsm_download,read_gsm,gsm_average
  File "/Users/shalom/anaconda3/lib/python3.7/site-packages/ggtools/gg/gsm_utils.py", line 8, in <module>
    from .utils import print_error_grace
  File "/Users/shalom/anaconda3/lib/python3.7/site-packages/ggtools/gg/utils.py", line 2, in <module>
    from sphericalpolygon import create_polygon
ImportError: cannot import name 'create_polygon' from 'sphericalpolygon' (/Users/shalom/anaconda3/lib/python3.7/site-packages/sphericalpolygon/__init__.py)

**Comment by xiaojingdounaodan** [comment]
you can try the version 1.0.0 of sphericalpolygon

**Comment by ssbzs** [comment]
Hello, I have the same problem now. How did you solve it
